/**
 * Created by zhaoyong on 2014/10/28.
 * ASCII对照表
 */
(function ($) {
    $(document).ready(function () {
        var ASCIIData = [
            {ascii: '0', character: 'NUL 空字符（Null）'},
            {ascii: '32', character: '(space)'},
            {ascii: '64', character: '@'},
            {ascii: '96', character: '、'},
            {ascii: '1', character: 'SOH 标题开始'},
            {ascii: '33', character: '!'},
            {ascii: '65', character: 'A'},
            {ascii: '97', character: 'a'},
            {ascii: '2', character: 'STX 本文开始'},
            {ascii: '34', character: '"'},
            {ascii: '66', character: 'B'},
            {ascii: '98', character: 'b'},
            {ascii: '3', character: 'ETX 本文结束'},
            {ascii: '35', character: '#'},
            {ascii: '67', character: 'C'},
            {ascii: '99', character: 'c'},
            {ascii: '4', character: 'EOT 传输结束'},
            {ascii: '36', character: '$'},
            {ascii: '68', character: 'D'},
            {ascii: '100', character: 'd'},
            {ascii: '5', character: 'ENQ 请求'},
            {ascii: '37', character: '%'},
            {ascii: '69', character: 'E'},
            {ascii: '101', character: 'e'},
            {ascii: '6', character: 'ACK 确认回应'},
            {ascii: '38', character: '&'},
            {ascii: '70', character: 'F'},
            {ascii: '102', character: 'f'},
            {ascii: '7', character: 'BEL 响铃'},
            {ascii: '39', character: ','},
            {ascii: '71', character: 'G'},
            {ascii: '103', character: 'g'},
            {ascii: '8', character: 'BS 退格'},
            {ascii: '40', character: '('},
            {ascii: '72', character: 'H'},
            {ascii: '104', character: 'h'},
            {ascii: '9', character: 'HT 水平定位符号'},
            {ascii: '41', character: ')'},
            {ascii: '73', character: 'I'},
            {ascii: '105', character: 'i'},
            {ascii: '10', character: 'LF 换行键'},
            {ascii: '42', character: '*'},
            {ascii: '74', character: 'J'},
            {ascii: '106', character: 'j'},
            {ascii: '11', character: 'VT 垂直定位符号'},
            {ascii: '43', character: '+'},
            {ascii: '75', character: 'K'},
            {ascii: '107', character: 'k'},
            {ascii: '12', character: 'FF 换页键'},
            {ascii: '44', character: ','},
            {ascii: '76', character: 'L'},
            {ascii: '108', character: 'l'},
            {ascii: '13', character: 'CR 归位键'},
            {ascii: '45', character: '-'},
            {ascii: '77', character: 'M'},
            {ascii: '109', character: 'm'},
            {ascii: '14', character: 'SO 取消变换（Shift out）'},
            {ascii: '46', character: '.'},
            {ascii: '78', character: 'N'},
            {ascii: '110', character: 'n'},
            {ascii: '15', character: 'SI 启用变换（Shift in）'},
            {ascii: '47', character: '/'},
            {ascii: '79', character: 'O'},
            {ascii: '111', character: 'o'},
            {ascii: '16', character: 'DLE 跳出数据通讯'},
            {ascii: '48', character: '0'},
            {ascii: '80', character: 'P'},
            {ascii: '112', character: 'p'},
            {ascii: '17', character: 'DCI 设备控制一（XON 启用软件速度控制）'},
            {ascii: '49', character: '1'},
            {ascii: '81', character: 'Q'},
            {ascii: '113', character: 'q'},
            {ascii: '18', character: 'DC2 设备控制二'},
            {ascii: '50', character: '2'},
            {ascii: '82', character: 'R'},
            {ascii: '114', character: 'r'},
            {ascii: '19', character: 'DC3 设备控制三（XOFF 停用软件速度控制）'},
            {ascii: '51', character: '3'},
            {ascii: '83', character: 'S'},
            {ascii: '115', character: 's'},
            {ascii: '20', character: 'DC4 设备控制四'},
            {ascii: '52', character: '4'},
            {ascii: '84', character: 'T'},
            {ascii: '116', character: 't'},
            {ascii: '21', character: 'NAK 确认失败回应'},
            {ascii: '53', character: '5'},
            {ascii: '85', character: 'U'},
            {ascii: '117', character: 'u'},
            {ascii: '22', character: 'SYN 同步用暂停'},
            {ascii: '54', character: '6'},
            {ascii: '86', character: 'V'},
            {ascii: '118', character: 'v'},
            {ascii: '23', character: 'TB 区块传输结束'},
            {ascii: '55', character: '7'},
            {ascii: '87', character: 'W'},
            {ascii: '119', character: 'w'},
            {ascii: '24', character: 'CAN 取消'},
            {ascii: '56', character: '8'},
            {ascii: '88', character: 'X'},
            {ascii: '120', character: 'x'},
            {ascii: '25', character: 'EM 连接介质中断'},
            {ascii: '57', character: '9'},
            {ascii: '89', character: 'Y'},
            {ascii: '121', character: 'y'},
            {ascii: '26', character: 'SUB 替换'},
            {ascii: '58', character: ':'},
            {ascii: '90', character: 'Z'},
            {ascii: '122', character: 'z'},
            {ascii: '27', character: 'ESC 跳出'},
            {ascii: '59', character: ';'},
            {ascii: '91', character: '['},
            {ascii: '123', character: '{'},
            {ascii: '28', character: 'FS 文件分割符'},
            {ascii: '60', character: '<'},
            {ascii: '92', character: '/'},
            {ascii: '124', character: '|'},
            {ascii: '29', character: 'GS 组群分隔符'},
            {ascii: '61', character: '='},
            {ascii: '93', character: ']'},
            {ascii: '125', character: '}'},
            {ascii: '30', character: 'RS 记录分隔符'},
            {ascii: '62', character: '>'},
            {ascii: '94', character: '^'},
            {ascii: '126', character: '`'},
            {ascii: '31', character: 'US 单元分隔符'},
            {ascii: '63', character: '?'},
            {ascii: '95', character: '_'},
            {ascii: '127', character: 'DEL 删除'}
        ];
        $('#ASCII').populateGrid({headers: [
            {header: '控制字符', name: 'character'},
            {header: 'ASCII码值', name: 'ascii'}
        ], rowGroup: 4}, ASCIIData);
    });
})(jQuery);