/**
 * Created by zhaoyong on 2014/10/27.
 * Html转义字符
 */
(function ($) {
    $(document).ready(function () {
        var htmlEscapeCharacterData = [
            {character: '"', decimal: '&#34;', escape: '&quot;'},
            {character:'&', decimal:'&#38;', escape:'&amp;'},
            {character:'<', decimal:'&#60;', escape:'&lt;'},
            {character:'>', decimal:'&#62;', escape:'&gt;'},
            {character:'不断开空格(non-breaking space)', decimal:'&#160;', escape:'&nbsp;'},
            {character:'?', decimal:'&#161;', escape:'&iexcl;'},
            {character:'￠', decimal:'&#162;', escape:'&cent;'},
            {character:'', decimal:'', escape:''},
            {character:'', decimal:'', escape:''},
            {character:'', decimal:'', escape:''},
            {character:'', decimal:'', escape:''},
            {character:'', decimal:'', escape:''},
            {character:'', decimal:'', escape:''},
            {character:'', decimal:'', escape:''},
            {character:'', decimal:'', escape:''},
            {character:'', decimal:'', escape:''},
            {character:'', decimal:'', escape:''},
            {character:'', decimal:'', escape:''},
            {character:'', decimal:'', escape:''},
            {character:'', decimal:'', escape:''},
            {character:'', decimal:'', escape:''},
            {character:'', decimal:'', escape:''},
            {character:'', decimal:'', escape:''},
            {character:'', decimal:'', escape:''},
            {character:'', decimal:'', escape:''},
            {character:'', decimal:'', escape:''},
            {character:'', decimal:'', escape:''},
            {character:'', decimal:'', escape:''},
            {character:'', decimal:'', escape:''},
            {character:'', decimal:'', escape:''},
            {character:'', decimal:'', escape:''},
            {character:'', decimal:'', escape:''},
            {character:'', decimal:'', escape:''},
            {character:'', decimal:'', escape:''},
            {character:'', decimal:'', escape:''},
            {character:'', decimal:'', escape:''},
            {character:'', decimal:'', escape:''},
            {character:'', decimal:'', escape:''},
            {character:'', decimal:'', escape:''},
            {character:'', decimal:'', escape:''},
            {character:'', decimal:'', escape:''},
            {character:'', decimal:'', escape:''},
            {character:'', decimal:'', escape:''},
            {character:'', decimal:'', escape:''},
            {character:'', decimal:'', escape:''},
            {character:'', decimal:'', escape:''},
            {character:'', decimal:'', escape:''},
            {character:'', decimal:'', escape:''},
            {character:'', decimal:'', escape:''},
            {character:'', decimal:'', escape:''},
            {character:'', decimal:'', escape:''},
            {character:'', decimal:'', escape:''},
            {character:'', decimal:'', escape:''},
            {character:'', decimal:'', escape:''},
            {character:'', decimal:'', escape:''},
            {character:'', decimal:'', escape:''},
            {character:'', decimal:'', escape:''},
            {character:'', decimal:'', escape:''},
            {character:'', decimal:'', escape:''},
            {character:'', decimal:'', escape:''},
            {character:'', decimal:'', escape:''},
            {character:'', decimal:'', escape:''}
        ];
        $('#htmlEscapeCharacter').populateGrid({headers: [
            {header: '字符', name: 'character'},
            {header: '十进制', name: 'decimal'},
            {header: '转义字符', name: 'escape'}
        ], rowGroup: 3}, htmlEscapeCharacterData);
    });
})(jQuery);
